# Generated by Django 2.2 on 2022-08-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='have_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projeto',
            name='video_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
