# Generated by Django 2.2 on 2022-08-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugic', '0003_auto_20220826_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cover_2',
            field=models.ImageField(blank=True, upload_to='projetos/covers/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='cover_3',
            field=models.ImageField(blank=True, upload_to='projetos/covers/%Y/%m/%d/'),
        ),
    ]
