# Generated by Django 2.2 on 2022-08-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugic', '0004_auto_20220828_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
