# Generated by Django 2.2 on 2022-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugic', '0005_auto_20220828_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='video_download',
            field=models.ImageField(blank=True, upload_to='projetos/covers/%Y/%m/%d/'),
        ),
    ]
