# Generated by Django 2.2 on 2022-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugic', '0006_projeto_video_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='video_download',
            field=models.FileField(blank=True, upload_to='projetos/covers/%Y/%m/%d/'),
        ),
    ]
