# Generated by Django 2.2 on 2022-09-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugic', '0007_auto_20220829_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
